In [135]:
import pandas as pd
import time
import os
import re
import json
import requests
from datetime import datetime, timedelta
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor, as_completed
import plotly.express as px
import plotly.graph_objects as go
from clickhouse_driver import Client

In [136]:
BASE_DIR = os.getcwd()
CONFIG_PATH = os.path.join(BASE_DIR, 'config.json')
TOKEN_PATH = os.path.join(BASE_DIR, 'token.json')
DATA_DIR = os.path.join(BASE_DIR, 'data/hh_api_data')
SEARCH_CONFIG_PATH = os.path.join(BASE_DIR, 'search_config.json')

In [137]:
def load_config():
    """Load configuration from config.json"""
    try:
        with open(CONFIG_PATH, 'r') as config_file:
            return json.load(config_file)
    except FileNotFoundError:
        raise Exception("config.json file not found")
    except json.JSONDecodeError:
        raise Exception("Error parsing config.json")

def save_token(token_data):
    """Save token to file"""
    token_data['saved_at'] = datetime.now().isoformat()
    with open(TOKEN_PATH, 'w') as token_file:
        json.dump(token_data, token_file)

def load_token():
    """Load existing token"""
    try:
        with open(TOKEN_PATH, 'r') as token_file:
            token_data = json.load(token_file)
            saved_at = datetime.fromisoformat(token_data['saved_at'])
            # Check if token has expired (we store for 1 day)
            if datetime.now() - saved_at < timedelta(days=1):
                return token_data['access_token']
    except (FileNotFoundError, json.JSONDecodeError, KeyError):
        pass
    return None

def is_token_valid(token):
    """Check token validity using a simple request to HH.ru API."""
    if not token:
        return False  # Return False if token is None or empty
    try:
        response = requests.get(
            'https://api.hh.ru/vacancies?per_page=1',
            headers={'Authorization': f'Bearer {token}'}
        )
        return response.ok  # Simplified check using response.ok
    except Exception:
        return False

def get_access_token(client_id, client_secret):
    """Get access token from HH.ru API"""
    # First try to load existing token
    existing_token = load_token()
    if is_token_valid(existing_token):
        return existing_token
    else:
        print("Local token is invalid, obtaining a new one...")

    # If token not found or expired, request a new one
    token_url = 'https://hh.ru/oauth/token'
    headers = {'Content-Type': 'application/x-www-form-urlencoded'}
    data = {
        'grant_type': 'client_credentials',
        'client_id': client_id,
        'client_secret': client_secret
    }
    
    response = requests.post(token_url, headers=headers, data=data)
    if response.status_code == 200:
        token_data = response.json()
        token_data['saved_at'] = datetime.now().isoformat()
        save_token(token_data)
        return token_data['access_token']
    else:
        raise Exception(f"Error getting token: {response.status_code}, {response.text}")

def create_api_client():
    """Create API client with loaded credentials"""
    config = load_config()
    
    client_id = config.get('client_id')
    client_secret = config.get('client_secret')
    user_email = config.get('user_email')
    
    if not client_id or not client_secret:
        raise Exception("client_id or client_secret missing in config.json")
    
    access_token = get_access_token(client_id, client_secret)
    
    return {
        'headers': {
            'Authorization': f'Bearer {access_token}',
            'HH-User-Agent': f'Your_App_Name ({user_email})'
        },
        'base_url': 'https://api.hh.ru'
    }

In [138]:
def get_vacancy_details(api_client, vacancy_id):
    """Get detailed information about a specific vacancy"""
    response = requests.get(
        f"{api_client['base_url']}/vacancies/{vacancy_id}",
        headers=api_client['headers']
    )
    
    if response.status_code != 200:
        raise Exception(f"Error getting vacancy details: {response.status_code}, {response.text}")
        
    return response.json()

def get_all_countries(api_client):
    """Получить список всех стран из API"""
    response = requests.get(
        f"{api_client['base_url']}/areas/countries?host=hh.ru",
        headers=api_client['headers']
    )
    
    if response.status_code != 200:
        raise Exception(f"Error getting countries: {response.status_code}, {response.text}")
        
    return response.json()

def get_all_regions(api_client):
    """Получить все регионы (страны и их области) из API.
    Использует endpoint /areas, который возвращает иерархическую структуру со странами на верхнем уровне.
    """
    response = requests.get(
        f"{api_client['base_url']}/areas",
        headers=api_client['headers']
    )
    if response.status_code != 200:
        raise Exception(f"Error getting regions: {response.status_code}, {response.text}")
    return response.json()


def get_country_from_regions(areas, area_id):
    """Вернуть название страны по area_id, с особым правилом для 'Другие регионы'."""
    target = str(area_id)

    for country in areas:
        if not isinstance(country, dict):
            continue

        # Если это прямое совпадение — и это не "Другие регионы", возвращаем как есть
        if str(country.get("id")) == target:
            if country.get("name") == "Другие регионы":
                # Если "Другие регионы", но areas есть — пробуем найти внутри
                if country.get("areas"):
                    return None  # Или пробуем дальше, но ничего не возвращаем на этом уровне
                else:
                    return "Unknown"  # Или что-то нейтральное
            return country.get("name")

        # Поиск внутри
        stack = list(country.get("areas", []))
        while stack:
            node = stack.pop()
            if not isinstance(node, dict):
                continue
            if str(node.get("id")) == target:
                return country.get("name") if country.get("name") != "Другие регионы" else node.get("name")
            stack.extend(node.get("areas", []))

    raise Exception(f"Страна с area_id {area_id} не найдена")

def get_employer_details(api_client, employer_id):
    """Get detailed information about a specific employer"""
    response = requests.get(
        f"{api_client['base_url']}/employers/{employer_id}",
        headers=api_client['headers']
    )
    
    if response.status_code != 200:
        raise Exception(f"Error getting employer details: {response.status_code}, {response.text}")
        
    return response.json()

def get_all_vacancies_single(api_client, search_text, max_pages=None):
    """Get all vacancies with pagination"""
    all_vacancies = []
    page = 0
    per_page = 100  # Maximum number of vacancies per page
    
    while True:
        response = requests.get(
            f"{api_client['base_url']}/vacancies",
            headers=api_client['headers'],
            params = {
                'text': search_text,
                'per_page': per_page,
                # 'area': 1,  # Moscow (can be removed or changed)
                # 'only_with_salary': True,  # Optional: only with specified salary
                'search_field': ['name'],  # Search in all fields
                'order_by': 'publication_time',  # Sort by publication date
                'page': page
            }
        )
        
        if response.status_code != 200:
            print(f"Error getting page {page}: {response.status_code}")
            break
            
        data = response.json()
        vacancies = data['items']
        
        for vacancy in vacancies:
            vacancy['search_text'] = search_text
        
        if not vacancies:
            break
            
        # Save first 3 pages of raw JSON response
        if page < 3:
            filename = f"vacancies_raw_page_{page}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
            if not os.path.exists(DATA_DIR):
                os.makedirs(DATA_DIR)
            filepath = os.path.join(DATA_DIR, filename)
            with open(filepath, 'w', encoding='utf-8') as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
            print(f"Saved raw JSON for page {page} to {filename}")
            
        if page == 0:
            print(data)
            
        all_vacancies.extend(vacancies)
        print(f"Loaded page {page}, received {len(vacancies)} vacancies")
        
        page += 1
        if max_pages and page >= max_pages:
            break
    
    return all_vacancies

def get_all_vacancies(api_client, search_text, max_pages=None):
    """
    Gets vacancies with pagination.
    If the search_text parameter contains multiple values separated by '|',
    sequential search is performed for each keyword.
    """
    if '|' in search_text:
        all_vacancies = []
        keywords = [kw.strip() for kw in search_text.split('|')]
        for kw in keywords:
            print(f"Starting search for: {kw}")
            vacancies = get_all_vacancies_single(api_client, kw, max_pages)
            all_vacancies.extend(vacancies)
        return all_vacancies
    else:
        return get_all_vacancies_single(api_client, search_text, max_pages)

In [139]:
# Глобальный маппинг query → category (заполняется в cell-6)
QUERY_TO_CATEGORY = {}

def create_vacancies_dataframe(vacancies):
    """Convert list of vacancies to DataFrame"""
    processed_vacancies = []
    
    for vacancy in vacancies:
        try:
            # Извлекаем вложенные словари
            salary_data = vacancy.get('salary') or {}
            area_data = vacancy.get('area') or {}
            snippet_data = vacancy.get('snippet') or {}
            address_data = vacancy.get('address') or {}
            employer_data = vacancy.get('employer') or {}
            experience_data = vacancy.get('experience') or {}
            work_format_data = vacancy.get('work_format') or []
            professional_roles = vacancy.get('professional_roles') or []
            
            # Обработка формата работы (нормализуем неразрывные пробелы)
            work_formats = [fmt.get('name', '').replace('\xa0', ' ') for fmt in work_format_data]
            work_format_str = ', '.join(work_formats) if work_formats else ''
            
            # Обработка профессиональных ролей
            role_ids = [str(role.get('id')) for role in professional_roles]
            role_names = [role.get('name', '') for role in professional_roles]
            
            # Получаем search_text и нормализуем в category через маппинг
            search_text = vacancy.get('search_text', '')
            category = QUERY_TO_CATEGORY.get(search_text.lower(), search_text.lower())
            
            processed_vacancy = {
                'id': vacancy.get('id'),
                'name': vacancy.get('name'),
                'url': vacancy.get('alternate_url'),
                'salary_from': salary_data.get('from'),
                'salary_to': salary_data.get('to'),
                'salary_currency': salary_data.get('currency'),
                'company_name': employer_data.get('name'),
                'company_id': employer_data.get('id'),
                'area': area_data.get('name'),
                'area_id': area_data.get('id'),
                'address': address_data.get('raw', ''),
                'created_at': vacancy.get('created_at'),
                'published_at': vacancy.get('published_at'),
                'requirement': snippet_data.get('requirement'),
                'responsibility': snippet_data.get('responsibility'),
                'experience': experience_data.get('name', ''),
                'work_format': work_format_str,
                'internship': vacancy.get('internship', False),
                'premium': vacancy.get('premium', False),
                'professional_role_ids': ','.join(role_ids),
                'professional_role_names': ','.join(role_names),
                'search_text': search_text,
                'category': category
            }
            processed_vacancies.append(processed_vacancy)
        except Exception as e:
            print(f"Error processing vacancy {vacancy.get('id', 'Unknown ID')}: {str(e)}")
            continue
    
    if not processed_vacancies:
        raise Exception("Failed to process any vacancies")
        
    df = pd.DataFrame(processed_vacancies)
    
    # Заполнение пустых значений
    df['salary_from'] = df['salary_from'].fillna(0)
    df['salary_to'] = df['salary_to'].fillna(0)
    df['salary_currency'] = df['salary_currency'].fillna('RUR')
    df['requirement'] = df['requirement'].fillna('')
    df['responsibility'] = df['responsibility'].fillna('')
    
    return df


def get_vacancy_details_with_retry(api_client, vacancy_id, max_retries=3):
    """Get details of a single vacancy with retry logic"""
    for attempt in range(max_retries):
        try:
            return get_vacancy_details(api_client, vacancy_id)
        except Exception as e:
            if attempt == max_retries - 1:
                print(f"Failed to get details for vacancy {vacancy_id} after {max_retries} attempts: {e}")
                return None
            time.sleep(1)


def process_vacancy_details(api_client, vacancy_id):
    """Process details for a single vacancy including billing_type"""
    try:
        details = get_vacancy_details_with_retry(api_client, vacancy_id)
        if details:
            # Извлекаем billing_type.id (standard, free, premium и т.д.)
            billing_type_data = details.get('billing_type') or {}
            billing_type = billing_type_data.get('id', '')
            
            return {
                'id': vacancy_id,
                'description': details.get('description', ''),
                'key_skills': [skill.get('name') for skill in details.get('key_skills', [])],
                'billing_type': billing_type
            }
        return None
    except Exception as e:
        print(f"Error processing vacancy {vacancy_id}: {e}")
        return None

print("Functions for vacancy processing defined.")

Functions for vacancy processing defined.

In [140]:
api_client = create_api_client()

In [167]:
# Загружаем конфигурацию поисковых запросов
# SEARCH_CONFIG_PATH уже определен выше динамически

def load_search_config():
    """Load search configuration from search_config.json"""
    with open(SEARCH_CONFIG_PATH, 'r', encoding='utf-8') as f:
        return json.load(f)

def build_query_to_category_mapping(config):
    """Построить маппинг query (lowercase) → category"""
    mapping = {}
    for category, data in config['categories'].items():
        for query in data['queries']:
            mapping[query.lower()] = category
    return mapping

def get_search_terms(config, categories=None):
    """
    Get search terms from config.
    
    Args:
        config: Loaded search config dict
        categories: List of category keys to include. If None, includes all.
    
    Returns:
        List of (category_key, search_query) tuples
    """
    all_categories = config.get('categories', {})
    
    if categories is None:
        categories = list(all_categories.keys())
    
    search_terms = []
    for cat_key in categories:
        if cat_key in all_categories:
            cat_data = all_categories[cat_key]
            # Берём первый query — он самый полный с OR
            query = cat_data['queries'][0]
            search_terms.append((cat_key, query))
        else:
            print(f"Warning: Category '{cat_key}' not found in config")
    
    return search_terms

# Загружаем конфиг и строим маппинг
search_config = load_search_config()
QUERY_TO_CATEGORY.update(build_query_to_category_mapping(search_config))

# Выбираем категории для загрузки (None = все, или список конкретных)
selected_categories = [
    # 'system_analyst',
    # 'business_analyst',
    'product_manager',
    # 'teamlead',
    # 'data_engineer',
    'devops',
    'project_manager',
    'cpo',
    'cto',
    # 'cdo',
    # 'golang',
    'qa',
    'php',
    'frontend',
    'python',
    'java',
    'kotlin',
    'ios',
    'android',
]

# Получаем search terms
search_terms_with_categories = get_search_terms(search_config, selected_categories)

print(f"Загружено {len(search_terms_with_categories)} категорий:")
for cat_key, query in search_terms_with_categories:
    display_name = search_config['categories'][cat_key]['display_name']
    print(f"  - {display_name}: {query[:60]}...")

try:
    # Собираем только queries для поиска
    search_queries = [query for _, query in search_terms_with_categories]
    search_text_combined = '|'.join(search_queries)
    
    vacancies = get_all_vacancies(api_client, search_text_combined, max_pages=5000)
    df = create_vacancies_dataframe(vacancies)
    
    # Count records before removing duplicates
    initial_count = len(df)
    
    # Remove duplicates by 'id', keeping the first occurrence
    df = df.drop_duplicates(subset=['id'])
    
    # Count records after removing duplicates
    final_count = len(df)
    duplicates_removed = initial_count - final_count
    print(f"Количество удаленных дубликатов: {duplicates_removed}")
    
    # Get country for all unique area_id values
    unique_area_ids = df['area_id'].unique()
    regions = get_all_regions(api_client)
    area_country_mapping = {}

    for area_id in unique_area_ids:
        country = get_country_from_regions(regions, area_id)
        area_country_mapping[area_id] = country
        
    df['country'] = df['area_id'].map(area_country_mapping)
    df = df.reset_index(drop=True)
    
    print(f"Всего получено вакансий: {len(df)}")
    
except Exception as e:
    print(f"Произошла ошибка: {str(e)}")

df.info()

Warning: Category 'kotlin' not found in config
Загружено 7 категорий:
  - QA Engineer: QA engineer OR QA-инженер OR тестировщик OR тестировщик ПО...
  - PHP Developer: php-разработчик OR php developer OR php разработчик...
  - Frontend Developer: frontend-разработчик OR frontend developer OR frontend разра...
  - Python Developer: python-разработчик OR python developer OR python разработчик...
  - Java Developer: java-разработчик OR java developer OR java разработчик...
  - iOS Developer: ios-разработчик OR ios developer OR swift developer OR ios р...
  - Android Developer: android-разработчик OR android developer OR kotlin developer...
Starting search for: QA engineer OR QA-инженер OR тестировщик OR тестировщик ПО
Saved raw JSON for page 0 to vacancies_raw_page_0_20260208_215022.json

In [168]:
print("Распределение по странам (в процентах):")
print(df['country'].value_counts(normalize=True).mul(100).round(2))
print("Распределение по полю area:")
print(df['area'].value_counts(normalize=True).mul(100).round(2))

Распределение по странам (в процентах):
country
Россия         81.15
Беларусь        5.77
Казахстан       5.45
Узбекистан      3.29
Грузия          1.55
Сербия          0.87
Кыргызстан      0.49
Кипр            0.38
Азербайджан     0.25
Армения         0.19
Польша          0.15
Вьетнам         0.11
Израиль         0.04
Латвия          0.04
Другое          0.04
США             0.04
Черногория      0.04
Литва           0.02
Турция          0.02
Таиланд         0.02
Мальта          0.02
Таджикистан     0.02
Китай           0.02
ОАЭ             0.02
Name: proportion, dtype: float64
Распределение по полю area:
area
Москва                                38.41
Санкт-Петербург                       10.29
Минск                                  4.81
Алматы                                 3.44
Ташкент                                3.14
                                      ...
Выселки                                0.02
Энгельс                                0.02
Сергиев Посад (Московская область)     0.02
Новороссийск                           0.02
ОАЭ                                    0.02
Name: proportion, Length: 238, dtype: float64

In [169]:
# Get list of all vacancy IDs
vacancy_ids = df['id'].tolist()
total_vacancies = len(vacancy_ids)

# Create progress bar
progress_bar = tqdm(total=total_vacancies, desc="Processing vacancies")

# Wrapper function to pass api_client
def process_vacancy_wrapper(vacancy_id):
    return process_vacancy_details(api_client, vacancy_id)

# Use ThreadPoolExecutor for parallel processing
with ThreadPoolExecutor(max_workers=10) as executor:
    future_to_id = {executor.submit(process_vacancy_wrapper, vid): vid for vid in vacancy_ids}
    
    details_list = []
    for future in as_completed(future_to_id):
        result = future.result()
        if result:
            details_list.append(result)
        progress_bar.update(1)

progress_bar.close()

# Create DataFrame with details
details_df = pd.DataFrame(details_list)

# Remove duplicates by id
duplicates = df[df.duplicated(subset=['id'], keep=False)]
if not duplicates.empty:
    print(f"Найдено {len(duplicates)} дубликатов по полю id")
    df = df.drop_duplicates(subset=['id'], keep='first')
    print(f"Дубликаты удалены. Осталось {len(df)} записей")

# Merge with main DataFrame
df = df.merge(details_df, on='id', how='left')

# Fill empty values
df['description'] = df['description'].fillna('')
df['key_skills'] = df['key_skills'].fillna('').apply(lambda x: ', '.join(x) if isinstance(x, list) else x)
df['billing_type'] = df['billing_type'].fillna('')

print(f"Details retrieved for {len(details_list)} out of {total_vacancies} vacancies")
print("\nDataFrame structure:")
df.info()
print(f"\nCategory distribution:")
print(df['category'].value_counts())
print(f"\nBilling type distribution:")
print(df['billing_type'].value_counts())

Processing vacancies: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4715/4715 [02:19<00:00, 33.75it/s]

Details retrieved for 4715 out of 4715 vacancies

DataFrame structure:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4715 entries, 0 to 4714
Data columns (total 27 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       4715 non-null   object
 1   name                     4715 non-null   object
 2   url                      4715 non-null   object
 3   salary_from              4715 non-null   float64
 4   salary_to                4715 non-null   float64
 5   salary_currency          4715 non-null   object
 6   company_name             4715 non-null   object
 7   company_id               4709 non-null   object
 8   area                     4715 non-null   object
 9   area_id                  4715 non-null   object
 10  address                  4685 non-null   object
 11  created_at               4715 non-null   object
 12  published_at             4715 non-null   object
 13  requirement              4715 non-null   object
 14  responsibility           4715 non-null   object
 15  experience               4715 non-null   object
 16  work_format              4715 non-null   object
 17  internship               4715 non-null   bool
 18  premium                  4715 non-null   bool
 19  professional_role_ids    4715 non-null   object
 20  professional_role_names  4715 non-null   object
 21  search_text              4715 non-null   object
 22  category                 4715 non-null   object
 23  country                  4715 non-null   object
 24  description              4715 non-null   object
 25  key_skills               4715 non-null   object
 26  billing_type             4715 non-null   object
dtypes: bool(2), float64(2), object(23)
memory usage: 930.2+ KB

Category distribution:
category
qa          1949
frontend     703
python       659
java         549
php          511
android      196
ios          148
Name: count, dtype: int64

Billing type distribution:
billing_type
standard         3898
standard_plus     712
free               79
premium            26
Name: count, dtype: int64

In [170]:
debug_one_vacancy = True
if debug_one_vacancy:   
    id = 119494106
    details = get_vacancy_details_with_retry(api_client, id)
    filename = f"vacancy_detail_{id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    filepath = os.path.join(DATA_DIR, filename)
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(details, f, ensure_ascii=False, indent=2)

In [171]:
debug_countries = False
if debug_countries:
    countries = get_all_countries(api_client)
    filename = f"countries_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    filepath = os.path.join(DATA_DIR, filename)
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(countries, f, ensure_ascii=False, indent=2)

In [172]:
debug_regions = False
if debug_regions:
    regions = get_all_regions(api_client)
    filename = f"regions_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    filepath = os.path.join(DATA_DIR, filename)
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(regions, f, ensure_ascii=False, indent=2)

In [173]:
debug_employer_details = True
if debug_employer_details:
    employer_id = 80
    employer_details = get_employer_details(api_client, employer_id)
    filename = f"employer_detail_{employer_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    filepath = os.path.join(DATA_DIR, filename)
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(employer_details, f, ensure_ascii=False, indent=2)

In [174]:
df.head(100)

,id,name,url,salary_from,salary_to,salary_currency,company_name,company_id,area,area_id,...,internship,premium,professional_role_ids,professional_role_names,search_text,category,country,description,key_skills,billing_type
0,130262411,Ведущий инженер по качеству,https://hh.ru/vacancy/130262411,0.0,0.0,RUR,ГК ТОФС,2501547,Москва,1,...,False,False,149,Контролёр ОТК,QA engineer OR QA-инженер OR тестировщик OR те...,qa,Россия,<p>Группа компаний ТОФС предоставляет высокоте...,"Контроль качества, Оптимизация производства, С...",standard
1,128931401,QA-инженер (backend),https://hh.ru/vacancy/128931401,0.0,0.0,RUR,Т-Банк,78638,Томск,90,...,False,False,124,Тестировщик,QA engineer OR QA-инженер OR тестировщик OR те...,qa,Россия,"<p>Ищем QA-инженеров, которые будут тестироват...","Тестирование, Функциональное тестирование, Авт...",standard
2,130262134,Инженер по качеству 2 категории,https://hh.ru/vacancy/130262134,128000.0,130000.0,RUR,"Моринформсистема-Агат, Концерн",179533,Москва,1,...,False,False,44,Инженер по качеству,QA engineer OR QA-инженер OR тестировщик OR те...,qa,Россия,<p><strong>Обязанности:</strong></p> <ul> <li>...,,standard
3,130262113,Инженер по качеству 2 категории,https://hh.ru/vacancy/130262113,128000.0,130000.0,RUR,"Моринформсистема-Агат, Концерн",179533,Москва,1,...,False,False,44,Инженер по качеству,QA engineer OR QA-инженер OR тестировщик OR те...,qa,Россия,<p><strong>Обязанности:</strong></p> <ul> <li>...,,standard
4,128642155,QA Engineer (Mobile),https://hh.ru/vacancy/128642155,0.0,0.0,RUR,STARTRIBE LTD,10574557,Сербия,146,...,False,False,124,Тестировщик,QA engineer OR QA-инженер OR тестировщик OR те...,qa,Сербия,<p><strong>О компании:</strong> Занимаемся раз...,"Android Studio, Xcode, Тестирование Android-пр...",standard_plus
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,129994232,Инженер по качеству/специалист по качеству,https://hh.ru/vacancy/129994232,80000.0,0.0,RUR,Бюджетное учреждение Ханты-Мансийского автоном...,1742382,Сургут,1381,...,False,False,151,Специалист по сертификации,QA engineer OR QA-инженер OR тестировщик OR те...,qa,Россия,<strong>Обязанности:</strong> <p>Внедрять в Уч...,Контроль качества,standard
96,127438901,Middle/Senior QA automation engineer,https://hh.ru/vacancy/127438901,0.0,0.0,RUR,INVESTBANQ TECH LAB LIMITED,10043512,Алматы,160,...,False,False,124,Тестировщик,QA engineer OR QA-инженер OR тестировщик OR те...,qa,Казахстан,<p><strong>Investbanq </strong>is an AI-powere...,,standard
97,130026730,Помощник инженера-тестировщика оборудования,https://hh.ru/vacancy/130026730,105000.0,155000.0,RUR,Юзьков Александр Евгеньевич,9268406,Москва,1,...,True,False,40,Другое,QA engineer OR QA-инженер OR тестировщик OR те...,qa,Россия,<h2><em>Приглашаем кандидатов с опытом и БЕЗ н...,"Обучение и развитие, Внимательность, Ответстве...",standard_plus
98,129826033,Начинающий тестировщик-установщик оборудования...,https://hh.ru/vacancy/129826033,105000.0,170000.0,RUR,Юзьков Александр Евгеньевич,9268406,Москва,1,...,True,False,40,Другое,QA engineer OR QA-инженер OR тестировщик OR те...,qa,Россия,<h4><strong><em>Приглашаем кандидатов с опытом...,"Работа в команде, Обучение и развитие, Желание...",standard_plus
99,129445772,Ассистент тестировщика,https://hh.ru/vacancy/129445772,90000.0,0.0,RUR,Туран Адам Адамович,12131886,Рязань,77,...,False,False,40,Другое,QA engineer OR QA-инженер OR тестировщик OR те...,qa,Россия,<p><strong>Условия:</strong></p> <p>Стабильная...,"работа со смартфоном, Тестирование, Обучаемост...",standard_plus

In [175]:
df.groupby('company_name').size().reset_index(name='count').sort_values('count', ascending=False)

                                 company_name  count
928                          Алабуга, ОЭЗ ППТ    114
2150                                   Т-Банк     92
2476                             Яндекс Крауд     82
65                                   Andersen     58
678   Team.Inno / Фабрика инноваций и решений     44
...                                       ...    ...
976                                 Атмосфера      1
974                                  Атлантик      1
973                               Астрал-Софт      1
971                                   Астория      1
2479      фирма Агрокомплекс им. Н.И. Ткачева      1

[2480 rows x 2 columns]

In [176]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4715 entries, 0 to 4714
Data columns (total 27 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       4715 non-null   object
 1   name                     4715 non-null   object
 2   url                      4715 non-null   object
 3   salary_from              4715 non-null   float64
 4   salary_to                4715 non-null   float64
 5   salary_currency          4715 non-null   object
 6   company_name             4715 non-null   object
 7   company_id               4709 non-null   object
 8   area                     4715 non-null   object
 9   area_id                  4715 non-null   object
 10  address                  4685 non-null   object
 11  created_at               4715 non-null   object
 12  published_at             4715 non-null   object
 13  requirement              4715 non-null   object
 14  responsibility           4715 non-null   object
 15  experience               4715 non-null   object
 16  work_format              4715 non-null   object
 17  internship               4715 non-null   bool
 18  premium                  4715 non-null   bool
 19  professional_role_ids    4715 non-null   object
 20  professional_role_names  4715 non-null   object
 21  search_text              4715 non-null   object
 22  category                 4715 non-null   object
 23  country                  4715 non-null   object
 24  description              4715 non-null   object
 25  key_skills               4715 non-null   object
 26  billing_type             4715 non-null   object
dtypes: bool(2), float64(2), object(23)
memory usage: 930.2+ KB

In [177]:
# Формируем имя файла
filename = f"vacancies_all_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
filepath = os.path.join(DATA_DIR, filename)

# Сохраняем DataFrame
df.to_csv(filepath, index=False, encoding='utf-8')

In [178]:
def insert_bulk_dataframe(client, df, table_name):
    # Convert DataFrame to a list of tuples and perform bulk insertion in a single query
    data = list(df.itertuples(index=False, name=None))
    columns = ", ".join(df.columns)
    client.execute(f"INSERT INTO {table_name} ({columns}) VALUES", data)

# Load configuration using the existing load_config function
config = load_config()

# Configure ClickHouse client using data from configuration
client = Client(
    host=config['clickhouse_host'],
    port=9440,
    user='default',
    password=config['clickhouse_password'],
    database=config.get('clickhouse_database', 'default'),
    secure=True
)

In [179]:
def prepare_dataframe_for_clickhouse(df):
    """Преобразует DataFrame для соответствия схеме таблицы в ClickHouse"""
    df_prepared = df.copy()
    
    # Преобразуем числовые ID
    df_prepared['id'] = df_prepared['id'].fillna(0).astype(int)
    df_prepared['company_id'] = df_prepared['company_id'].fillna(0).astype(int)
    df_prepared['area_id'] = df_prepared['area_id'].fillna(0).astype(int)
    
    # professional_role_ids: берём первый ID (схема ожидает Int64)
    def extract_first_role_id(val):
        if pd.isna(val) or val == '':
            return 0
        first_id = str(val).split(',')[0].strip()
        return int(first_id) if first_id.isdigit() else 0
    
    df_prepared['professional_role_ids'] = df_prepared['professional_role_ids'].apply(extract_first_role_id)
    
    # Преобразуем поля с плавающей точкой
    df_prepared['salary_from'] = pd.to_numeric(df_prepared['salary_from'], errors='coerce').fillna(0)
    df_prepared['salary_to'] = pd.to_numeric(df_prepared['salary_to'], errors='coerce').fillna(0)
    
    # Преобразуем дату в формат DateTime
    df_prepared['created_at'] = pd.to_datetime(df_prepared['created_at'])
    df_prepared['published_at'] = pd.to_datetime(df_prepared['published_at'])
    
    # Заполняем None значения в строковых полях пустыми строками
    for column in df_prepared.select_dtypes(include=['object']).columns:
        df_prepared[column] = df_prepared[column].fillna('')
    
    # Преобразуем булевы значения в строки
    bool_columns = df_prepared.select_dtypes(include=['bool']).columns
    for column in bool_columns:
        df_prepared[column] = df_prepared[column].astype(str)
    
    # Убедимся что category заполнена
    if 'category' not in df_prepared.columns or df_prepared['category'].isna().any():
        df_prepared['category'] = df_prepared['search_text'].apply(
            lambda x: QUERY_TO_CATEGORY.get(x.lower(), x.lower())
        )
    
    # Убедимся что billing_type заполнен
    if 'billing_type' not in df_prepared.columns:
        df_prepared['billing_type'] = ''
    df_prepared['billing_type'] = df_prepared['billing_type'].fillna('')
    
    return df_prepared

# Добавляем колонку billing_type если её ещё нет
try:
    client.execute("ALTER TABLE vacancies_hh_ru ADD COLUMN IF NOT EXISTS billing_type String DEFAULT ''")
    print("Column billing_type added/verified in ClickHouse")
except Exception as e:
    print(f"Note: {e}")

# Подготавливаем данные и вставляем в ClickHouse
df_prepared = prepare_dataframe_for_clickhouse(df)

print(f"Prepared columns: {list(df_prepared.columns)}")
print(f"Category sample: {df_prepared['category'].head()}")
print(f"Billing type sample: {df_prepared['billing_type'].head()}")

insert_bulk_dataframe(client, df_prepared, 'vacancies_hh_ru')
print("Data successfully inserted into ClickHouse.")

Column billing_type added/verified in ClickHouse
Prepared columns: ['id', 'name', 'url', 'salary_from', 'salary_to', 'salary_currency', 'company_name', 'company_id', 'area', 'area_id', 'address', 'created_at', 'published_at', 'requirement', 'responsibility', 'experience', 'work_format', 'internship', 'premium', 'professional_role_ids', 'professional_role_names', 'search_text', 'category', 'country', 'description', 'key_skills', 'billing_type']
Category sample: 0    qa
1    qa
2    qa
3    qa
4    qa
Name: category, dtype: object
Billing type sample: 0         standard
1         standard
2         standard
3         standard
4    standard_plus
Name: billing_type, dtype: object
Data successfully inserted into ClickHouse.